package com.revature.sierra.alchemy.MVC.Exceptions;

public class UserNotFoundException {
	System.out.println("Restaurant not Found");
}
